version: "3.9"

services:
  backend:
    build: ./backend
    container_name: audio-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - audio-net

  frontend:
    build: ./frontend
    container_name: audio-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - audio-net

networks:
  audio-net:
    driver: bridge